import localFont from "next/font/local";
import "./globals.css";
import { NavbarMain } from "./components/Navbar";
import { ScrollProgress } from "./components/ui/ScrollProgress";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScrollProgress
          position={"left"}
          color={"#189AB4"}
          height={10}
          smoothness={true}
        />
        <NavbarMain />
        {children}
      </body>
    </html>
  );
}
